### PR TITLE
Added setup to easily configure on any resolution (I hope)

### PR DESCRIPTION
**Pull request by tyler-bell**
Wanted to use this on my 1366x768 laptop, but didn't want to hardcode it. With a good guess of the centre using outfits and the radius from the ingame HUD, I was getting good results. Had to add a config file to save/retrieve the new settings and keep things simple for users. Setup could use some cleaner instructions, maybe step by step instead and readme needs updated. Some sloppy practices, but never using python before is my excuse.

### CODE REVIEW

**Comment by krolikson** [comment]
Hi Tyler, can you help solve my problem with cooldown overlay? When i try put 2 spell into one cooldown Group it not work'd good. For example i have "exura ico" at f2 key and i put it to heal cooldown Group. In this Group also i have "exura Gran ico" at f3. But when i use "exura ico"  timer from "Gran ico"  start from Max too. Please help mate's. I want to make cooldown from groups on arc and rest spell Just display on screen by Text and timer.

**Comment by krolikson** [comment]
Also this version is only one from three diffrent which dispal transparent Windows on my PC. Win 7Home Premium 64

**Comment by krolikson** [comment]
One more questions guy's. Is that possible to make tracker like that but with tracking in Real time by tracking counting icons, changings pixels or something like that?  Or in this case is nessesery to read client memory?

**Comment by krolikson** [comment]
Anyway after your changes in script, it start display me any Text and arc. Before it vsz brand display only arcs and brand "migrate Mouse keyboard master~" display me only Text and timers without arcs but i had this same kind of problem like in your version.

**Comment by vsz** [comment]
@krolikson can you paste the configuration part of your code? I know there are some problems when using keypad and arrow keys, as they may trigger other spells.

**Comment by krolikson** [comment]
Problem with arrows keys disapear after remap my keyboard. I just set again "UP Arrow" to "UP Arrow" etc.  Which part of code do you need and from what version? This one with position settings, spell setting  or visible of group? I tried to make some changes like in my previous post, but after it, script stop countdown any spells or group. I thinking about create New class of group or put in code 
"if cooldownGroup == cooldown.attack
      Set.cooldown.attack.setTime" 
In script in place where is 
"if cooldownGroup == cooldown.specjal" 
Is any chance to work it?

**Comment by krolikson** [comment]
Any ideas how to fix it?

**Comment by vsz** [comment]
@krolikson please open an Issue on the appropriate location. This discussion will be closed as it is destined to the pull request.
@tyler-bell based on your json code, I implemented a more complete positioner which I think will come in handy. Check it out on the master branch! Thanks for the help!

**Pull request closed without merging**
